### ISSUE TITLE
Todo/improvements

### ISSUE THREAD

**Issue by sondresj** [sondresj/scad-models#1]
- [x] Cutout/clamp for cable connecting the two halves
- [ ] Mechanism to lock the two halves togheter when on the move, perhaps a way to pack the keyboard within as well?
- [x] Support for using the original magnet pegs as is
- [x] Reduce amount of material used
- [ ] Thumb-rest?
- [ ] Bump under palm for more restiness
